name: test docker file
on:
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest     
    steps:    
      - name: Get actions code
        uses: actions/checkout@v3    
      - name: say-hello
        uses: ./.github/actions/start-server-job-actions  
#      - name: run docker
#        run: docker build -t local < ./code-dot-org/docker/dockerfiles/Dockerfile
      - name: install docker
        run: |
          brew install docker-compose
          export FIXUID=$(id -u)   
          export FIXGID=$(id -g)
          docker-compose -f ./docker/setup-compose.yml up > output.txt
        continue-on-error: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3   
