name: test docker file
on:
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest     
    steps:    
      - name: Get actions code
        uses: actions/checkout@v3    
      - name: say-hello
        uses: ./.github/actions/start-server-job-actions  
      - name: run docker
        run: docker build -t local < ./code-dot-org/docker/dockerfiles/Dockerfile
        
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3   
