name: test docker file
on:
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest

    using: 'docker'
    image: 'Dockerfile'        
    steps:    
      - name: Get actions code
        uses: actions/checkout@v3    
      - name: say-hello
        uses: ./.github/actions/start-server-job-actions  
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3   
